Screen:
    beschriftung: ''
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            canvas:
                Color:
                    rgba: 1,0,0,0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: root.beschriftung
        BoxLayout:
            Label:
                text: root.beschriftung
